/**
 * The Ledger — deal the books that a blunt rule wins.
 *
 * A book's seed fixes its applicants and their true outcomes. On some hands
 * that lands a coarse bar — approve everybody, or only the safest-looking —
 * near enough to the right answer to clear the target, and a book like that
 * asks nothing of the player it claims to test. This walks every book, plays
 * the whole reference family on it, and deals the book again until no blunt
 * rule comes close AND enough ways of reading the files still get through —
 * a book nothing wins would be as bad as one anything wins.
 *
 * Writes `js/seeds.js`. Run it after anything that moves the model:
 *
 *   node tools/reroll-seeds.mjs
 *
 * It is slow (a few minutes) because it plays the whole reference family on
 * every hand it tries. That is the point — the bar is measured, not guessed.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { POLICIES, playPolicy, parProfit } from '../js/sim.js';
import {
  TOWNS, BOOKS_PER_TOWN, TIERS, bookAtSeed, configForBook,
} from '../js/campaign.js';

/** The blunt rules: everything that does not weigh the file against the rate. */
const BLUNT = POLICIES.filter((p) => ['all', 'none', 'safest', 'rate'].includes(p.kind));

/** The rules that actually read a file and price it. */
const JUDGED = POLICIES.filter((p) => p.kind === 'ev');

/**
 * A hand no blunt rule wins is only half of what we want: a hand nothing at
 * all wins is worse, because then the book is decided by the deal rather than
 * by the player. So a candidate must also leave a decent number of ways to
 * win by reading the files. The floors are each tier's own 25th percentile on
 * the content as first dealt — harder tiers genuinely have fewer ways through,
 * and pretending otherwise would flatten the campaign.
 */
const WINNABLE = { easy: 8, medium: 4, hard: 2, impossible: 1 };

/**
 * How far under the target a blunt rule has to land. A hand where the coarse
 * bar misses by a penny is still a hand where the coarse bar was right, so
 * this asks for real daylight rather than a bare pass.
 */
const MARGIN = 0.9;

/** Give up on a book rather than search forever; nothing has come close. */
const MAX_DEALS = 400;

const baseSeed = (townIdx, i) => (townIdx + 1) * 1_000_003 + (i + 1) * 7919;
const NUDGE_STEP = 104_729;

/** Does a blunt rule clear this hand's bar? */
function verdict(townIdx, i, seed, siblings) {
  const town = TOWNS[townIdx];
  const book = bookAtSeed(townIdx, i, seed, siblings);
  const config = configForBook(town.id, book);
  const par = parProfit(config);
  const target = Math.max(5, Math.round(par * TIERS[book.tier].parFactor));
  const blunt = Math.max(...BLUNT.map((p) => playPolicy(config, p)));
  const ways = JUDGED.filter((p) => playPolicy(config, p) >= target).length;
  const ok = par > 0 && blunt < target * MARGIN && ways >= WINNABLE[book.tier];
  return { book, par, target, blunt, ways, ok };
}

const nudges = [];
const failures = [];
let dealt = 0;
const started = Date.now();

for (let townIdx = 0; townIdx < TOWNS.length; townIdx++) {
  // Names are deduped against the book's own town, so the accepted hands have
  // to accumulate as we go — exactly as `booksFor` builds them.
  const siblings = [];
  for (let i = 0; i < BOOKS_PER_TOWN; i++) {
    let nudge = 0;
    let v = verdict(townIdx, i, baseSeed(townIdx, i), siblings);
    while (!v.ok && nudge < MAX_DEALS) {
      nudge++;
      v = verdict(townIdx, i, baseSeed(townIdx, i) + nudge * NUDGE_STEP, siblings);
    }
    if (!v.ok) failures.push(`${TOWNS[townIdx].id}:${i}`);
    if (nudge) dealt++;
    nudges.push(nudge);
    siblings.push(v.book);
  }
  process.stderr.write(`  ${TOWNS[townIdx].id.padEnd(13)} done (${Math.round((Date.now() - started) / 1000)}s)\n`);
}

const total = nudges.length;
const worst = Math.max(...nudges);
const sorted = [...nudges].sort((a, b) => a - b);
console.log(`books re-dealt: ${dealt}/${total}`);
console.log(`deals needed:   median ${sorted[Math.floor(total / 2)]}, worst ${worst}`);
if (failures.length) console.log(`NO HAND FOUND:  ${failures.join(', ')}`);

const rows = [];
for (let r = 0; r < total; r += 25) {
  rows.push(`  ${nudges.slice(r, r + 25).join(', ')},`);
}

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '..', 'js', 'seeds.js'), `/**
 * The Ledger — which books were dealt a different hand, and how far along.
 *
 * Generated by \`tools/reroll-seeds.mjs\`. Do not edit by hand: run the tool.
 *
 * A book's seed fixes its applicants and their true outcomes, and therefore
 * also fixes how well a blunt rule happens to do on it. On some hands a
 * coarse bar — approve everybody, or only the safest-looking — lands near
 * enough to the right answer to clear the target, which makes that book a
 * poor test of judgement. Those books are dealt again until every blunt rule
 * falls clearly short. ${dealt} of the ${total} needed it; the rest kept the
 * first hand they were dealt, and their entry here is zero.
 *
 * One row per town, in \`TOWNS\` order; 25 books a row, in tier order.
 */
export const NUDGES = [
${rows.join('\n')}
];
`);
console.log('wrote js/seeds.js');
